# Site setings
name: 'Sonja Peterson'
description: 'Software Engineer'
meta_description: 'Sonja Peterson's software engineering blog'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: http://sonjapeterson.github.io
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: 'Sonja Peterson'
  image: 'authorimage.jpg'
  greetings: 'Hi there!'
  description: "My name is Sonja Person. I'm a full stack software engineer based in the Boston, MA area. It’s nice to meet you."

# Contact form setings
email: sonja.peterson@gmail.com
contact_page_description: "Enter your message below to send me an email:"
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'SonjaBPeterson'
github: 'sonjapeterson'
linkedin: 'petersonsonja'

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed