# Site setings
name: 'Sonja Peterson'
description: 'Software Engineer'
meta_description: "Sonja Peterson's software engineering blog"
baseurl: 
production_url: http://sonjapeterson.github.io/
disqus: 'sonjapeterson'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: 'Sonja Peterson'
  image: 'authorimage.jpg'
  greetings: 'Hi there!'
  description: "My name is Sonja Peterson. I'm a full stack software engineer based in the Boston, MA area. It's nice to meet you!"
  bio: "Sonja Peterson is a full stack software engineer based on the Boston, MA area. She enjoys programming in Ruby, Golang, Javascript and Typescript. When she's not programming, you can find her looking for new places to hike and ski around New England." 

# Social links
twitter: 'SonjaBPeterson'
github: 'sonjapeterson'
linkedin: 'petersonsonja'

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Blog
    url: /blog/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed