# Site setings
name: 'Sonja Peterson'
description: 'Software Engineer'
meta_description: "Sonja Peterson's software engineering blog"
production_url: https://sonja.codes/
disqus: 'sonjapeterson'
cover_image: bc_1.jpg
ga_analytics: UA-144771779-1 


# Author
author:
  name: 'Sonja Peterson'
  image: 'authorimage.jpg'
  greetings: "Hi, I'm Sonja!"
  description: "I'm a full stack software engineer based in the Boston, MA area. It's nice to meet you!"
  bio: "I’m a full stack software engineer based in the Boston, MA area, currently working at Devoted Health. I enjoy programming in Ruby, Golang, Javascript and Typescript. 
  When I’m not programming, you can find me looking for new places to hike and ski around New England."

# Social links
twitter: 'SonjaBPeterson'
github: 'sonjapeterson'
linkedin: 'petersonsonja'

# Navigation
navigation:
  - text: About
    url: /about
  - text: Blog
    url: /blog

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass
sass:
  sass_dir: _sass
  style: compressed
